name: Generate Summary
on:
  workflow_dispatch:
    inputs:
      runName:
        description: 'Enter a name for this test run'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install Dependencies
        run: npm install
      - name: Create .env file from workflow inputs
        run: |
          echo RUN_NAME=${{ github.event.inputs.runName }} >> .env
      - name: Run Selected Test
        run: |
          npx wdio run ./wdio.conf.js --spec sample.spec.js
      - name: Upload Test Summary Excel
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: '**/test-summary.xlsx'