name: Update Summary in Google Sheet
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Enter Project Name'
        required: true
      suite:
        description: 'Enter Suite Name'
        required: true
      env:
        description: 'Select Test Environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - UAT
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install Dependencies
        run: npm install
      - name: Install GoogleAPIs
        run: npm install googleapis
      - name: Run Selected Test
        run: |
          npx wdio run ./wdio.conf.js --spec sample.spec.js
        env:
          PROJECT: ${{ github.event.inputs.project }}
          SUITE_NAME: ${{ github.event.inputs.suite }}
          ENV: ${{ github.event.env }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      - name: Upload Test Summary Excel
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: '**/test-summary.xlsx'